name: geo2drop-agro
on:
#  push:
#    branches:
#      - master
  schedule:
    - cron: "15 6 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          # checkout all branches
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          sudo python3 -m pip install pybadges

      - name: Generate lists
        run: |
          sudo ./run.sh -do
          mv download/all-zones.tar.gz .
          ls .
          sudo python3 addits/badges.py

      - name: Remove remote data branch
        if: ${{ success() }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push origin :data

      - name: Checkout
        if: ${{ success() }}
        run: |
          git checkout --orphan data
          git rm -rf .
          sudo rm -rf download addits local.list README.md run.sh .gitignore .github

      - name: Add files
        if: ${{ success() }}
        run: |
          git add .

      - name: Commit Push
        if: ${{ success() }}
        run: |
          git commit -m "Geo IP generated!"
          git push origin data